global:
  scrape_interval: 5s
  scrape_timeout: 1s

rule_files:
  - alert.yaml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - "prometheus:9090"
          - "api:5000"
    honor_labels: true
